export const BASIC_CARS = [
  {
    id: "car-1",
    name: "Jaguar XE",
    gear: "AUTOMAT",
    drive: "AWD",
    fuel: "PB",
    hp: 300,
    price: 690.0,
    img: "/images/reservation/jaguar_jxe.jpg",
  },
  {
    id: "car-2",
    name: "Skoda KODIAQ",
    gear: "AUTOMAT",
    drive: "AWD",
    fuel: "ON",
    hp: 240,
    price: 490.0,
    img: "/images/reservation/skoda_kodiaq.jpg",
  },

  {
    id: "car-3",
    name: "Jaguar XF",
    gear: "AUTOMAT",
    drive: "RWD",
    fuel: "PB+LPG",
    hp: 297,
    price: 290.0,
    img: "",
  },

  {
    id: "car-4",
    name: "Renault TRAFIC",
    gear: "MANUAL",
    drive: "FWD",
    fuel: "ON",
    hp: 150,
    price: 390.0,
    img: "/images/reservation/renault_master.jpg",
  },

  {
    id: "car-5",
    name: "Dacia DUSTER",
    gear: "MANUAL",
    drive: "FWD",
    fuel: "PB+LPG",
    hp: 90,
    price: 190.0,
    img: "/images/reservation/dacia_duster.jpg",
  },

  {
    id: "car-6",
    name: "Dacia SANDERO",
    gear: "MANUAL",
    drive: "FWD",
    fuel: "PB+LPG",
    hp: 90,
    price: 130.0,
    img: "/images/reservation/dacia_sandero.jpg",
  },

  {
    id: "car-7",
    name: "Nissan MICRA",
    gear: "MANUAL",
    drive: "FWD",
    fuel: "PB",
    hp: 60,
    price: 40.0,
    img: "/images/reservation/nissan_micra.jpg",
  },
];
